version: "3.8"

services:
  chatdb:
    image: postgres:15
    container_name: chatdb 
    environment:
      POSTGRES_DB: chat_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./database/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./database/db.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
  chatapp:
    build: ./src
    container_name: chatapp
    environment:
      DB_HOST: chatdb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: chat_app
    ports:
      - 3000:3000
    depends_on:
      - chatdb

volumes:
  postgres_data:
